### ISSUE TITLE
CannotPullContainerError. Unable to start ECS task

### ISSUE THREAD

**Issue by mharray** [aws-samples/aws-refarch-shibboleth#9]
Hello, I've been attempting to get this shibboleth idp installation going on my AWS. Have got the cloud formation deploying, but when after increasing the task count on the ECS cluster as per the instructions, the task is failing to start with the following error:

CannotPullContainerError: inspect image has been retried 1 time(s): failed to resolve ref "517654814776.dkr.ecr.us-east-1.amazonaws.com/shibboleth:latest": 517654814776.dkr.ecr.us-east-1.amazonaws.com/shibboleth:latest: not found

Have tried a couple of different regions and both ec2 and fargate.

Any help is appreciated. Thanks

**Comment by billsnyder** [comment]
Hi @mharray this sounds like the CodePipeline didn't successfully complete.  Likely due to a failed CodeBuild.  Can you look at the CodeBuild output to see if there are any errors?

**Comment by mharray** [comment]
Hi @billsnyder thanks for the response. I have just checked the logs and there is an error. Looks like AWS have made a change to code commit that has caused the error.

> Invalid action configuration
> The action failed because no branch named master was found in the selected AWS CodeCommit repository shibboleth. Make sure you are using the correct branch name, and then try again. Error: null

> Starting on March 4, 2021 at 17:00 UTC, repositories created with an initial commit of code using AWS CloudFormation stacks will use 'main' instead of 'master' as the name of the default branch. To avoid impact from this change, you should update your templates to use the BranchName property or modify any code that expects 'master' as the default branch. For more information, see the documentation and this support article.

**Comment by billsnyder** [comment]
Pull request #10 fixes this.  Thanks for the contribution!
